### ISSUE TITLE
Pdf From Url Failing

### ISSUE THREAD

**Issue by maggz69** [Api2Pdf/api2pdf.php#20]
If I use headlessChromeFromUrl, all my requests are failing with the error `**invalid authorization header**` this is despite the URL page not needing authentication to be viewed. 

The specific line that fails is line #50 `$result = $this->api2PdfClient->headlessChromeFromUrl($url);`

## My Code
```php
<?php


namespace App\ApiActions;


use Api2Pdf\Api2Pdf;
use App\Models\Invoice;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Str;

class PdfApiGenerator
{
    /**
     * @var Api2Pdf Client
     */
    private $api2PdfClient;
    /**
     * @var \Ramsey\Uuid\UuidInterface
     */
    private $uuid;

    public function __construct()
    {
        $this->api2PdfClient = new Api2Pdf(config('api2pdf.client_key'));
        $this->uuid = Str::uuid();
    }

    public function generatePdfFromHtml(string $html): string
    {
        $result = $this->api2PdfClient->headlessChromeFromHtml($html);
        $fileContent = file_get_contents($result->getPdf());

        $this->uploadFileToStorage($fileContent);

        return \Storage::disk('invoices')->path($this->uuid);
    }

    private function uploadFileToStorage($fileContent): bool
    {
        return \Storage::disk('invoices')->write($this->uuid . '.pdf', $fileContent);
    }

    public function generatePdfFromUrl(Invoice $invoice): string
    {
        $url = URL::temporarySignedRoute('invoice_pdf_view', now()->addMinutes(1), [
            'invoice' => $invoice->id
        ]);

        $result = $this->api2PdfClient->headlessChromeFromUrl($url);

        $fileContent = file_get_contents($result->getPdf());

        $this->uploadFileToStorage($fileContent);

        return \Storage::disk('invoices')->path($this->uuid);
    }

}
```

## Stacktrace
```
Api2Pdf\Exception\ConversionException:  Invalid authorization header in  /home/forge/staging.app.swiftpesa.com/vendor/api2pdf/api2pdf.php/src/ApiResult.php:52
--
Stack trace:
#0   /home/forge/myapp/vendor/api2pdf/api2pdf.php/src/Api2Pdf.php(131):  Api2Pdf\ApiResult::createFromResponse()
#1 /home/forge/myapp/vendor/api2pdf/api2pdf.php/src/Api2Pdf.php(171): Api2Pdf\Api2Pdf->makeRequest()
#2 /home/forge/myapp/app/ApiActions/PdfApiGenerator.php(50): Api2Pdf\Api2Pdf->headlessChromeFromUrl()
```

**Comment by maggz69** [comment]
So after checking the code, I realised that the error wasn't being thrown while accessing my server but rather when passing my request to your server. This error was due to a misconfigured API_KEY that I had from the poral. The response should be abit more thorough on that though.
